# Generated by Django 4.1.4 on 2023-09-17 23:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 17, 23, 59, 3, 53226, tzinfo=datetime.timezone.utc), verbose_name='last_login'),
        ),
    ]
