# Generated by Django 4.1.4 on 2023-09-27 15:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0003_alter_newuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='commune',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='departement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_superuser',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 27, 15, 19, 59, 426541, tzinfo=datetime.timezone.utc), verbose_name='last_login'),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='sous_prefecture',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
