# Generated by Django 4.1.4 on 2023-09-30 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custumer', '0004_alter_newuser_commune_alter_newuser_departement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='last_login',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 30, 6, 44, 30, 858984, tzinfo=datetime.timezone.utc), verbose_name='last_login'),
        ),
    ]
