# Generated by Django 4.1.4 on 2023-09-09 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coordonnees_geographiques', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='hotel_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Residence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_etablissement', models.CharField(max_length=200)),
                ('adresse', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coordonnees_geographiques', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='residence_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('adresse_email', models.EmailField(max_length=254, unique=True)),
                ('mot_de_passe', models.CharField(max_length=128)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_chambre', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField()),
                ('equipements', models.TextField()),
                ('tarif_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('image1', models.ImageField(default='jpg', upload_to='images_de_la_chambre/')),
                ('image2', models.ImageField(default='jpg', upload_to='images_de_la_chambre/')),
                ('image3', models.ImageField(default='jpg', upload_to='images_de_la_chambre/')),
                ('image4', models.ImageField(default='jpg', upload_to='images_de_la_chambre/')),
                ('image5', models.ImageField(default='jpg', upload_to='images_de_la_chambre/')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.PositiveIntegerField()),
                ('commentaire', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='ResidenceRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_de_chambre', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField()),
                ('equipements', models.TextField()),
                ('tarif_journalier', models.DecimalField(decimal_places=2, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('image1', models.ImageField(default='jpg1', upload_to='images_de_la_residence/')),
                ('image2', models.ImageField(default='jpg1', upload_to='images_de_la_residence/')),
                ('image3', models.ImageField(default='jpg1', upload_to='images_de_la_residence/')),
                ('image4', models.ImageField(default='jpg1', upload_to='images_de_la_residence/')),
                ('image5', models.ImageField(default='jpg1', upload_to='images_de_la_residence/')),
                ('residence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residence')),
            ],
        ),
        migrations.AddField(
            model_name='residence',
            name='gerant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='residence',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.residencetype'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='gerant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipement', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut_sejour', models.DateField()),
                ('date_fin_sejour', models.DateField()),
                ('nombre_invite', models.PositiveIntegerField()),
                ('statut_reservation', models.CharField(choices=[('en_attente', 'En Attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé')], max_length=50)),
                ('montant_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
