# Generated by Django 4.1.4 on 2023-09-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_price_per_night_property_nombre_chambre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='room',
            name='numero',
        ),
    ]
