# Generated by Django 4.1.4 on 2023-09-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_room_hotel_remove_room_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='property',
        ),
        migrations.AddField(
            model_name='review',
            name='chambre',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.room'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.property'),
            preserve_default=False,
        ),
    ]
