# Generated by Django 4.1.4 on 2023-09-30 10:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_remove_review_property_review_chambre_room_hotel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='property',
            new_name='bien',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_in_date',
            new_name='date_arrive',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='check_out_date',
            new_name='date_depart',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='total_price',
            new_name='prix_total',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='amenities',
            new_name='equipement',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='price_per_night',
            new_name='prix',
        ),
        migrations.RemoveField(
            model_name='property',
            name='property_type',
        ),
        migrations.AddField(
            model_name='property',
            name='etoile',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='capacite',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image1',
            field=models.ImageField(default=1, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='image2',
            field=models.ImageField(default=2, upload_to='property_images/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Imagehotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='property_images/')),
                ('image2', models.ImageField(upload_to='property_images/')),
                ('image3', models.ImageField(upload_to='property_images/')),
                ('image4', models.ImageField(upload_to='property_images/')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.property')),
            ],
        ),
    ]
