# Generated by Django 4.1.4 on 2023-09-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_property_booking_bien_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='client',
        ),
        migrations.AddField(
            model_name='booking',
            name='adulte',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='enfant',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='disponibilite',
            field=models.BooleanField(default=True),
        ),
    ]
