# Generated by Django 4.1.4 on 2023-09-30 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_rename_user_booking_client_booking_adulte_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houserules',
            old_name='property',
            new_name='bien',
        ),
        migrations.RenameField(
            model_name='houserules',
            old_name='rules',
            new_name='regles',
        ),
        migrations.RenameField(
            model_name='imagehotel',
            old_name='property',
            new_name='bien',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='propertyavailability',
            old_name='property',
            new_name='bien',
        ),
        migrations.RenameField(
            model_name='propertyimage',
            old_name='property',
            new_name='bien',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='reporter',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='owner',
        ),
        migrations.AddField(
            model_name='houserules',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyavailability',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyimage',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
